### ISSUE TITLE
Initial approach

### ISSUE THREAD

**Issue by jonaskello** [alexisvincent/systemjs-yarn-integration#1]
Just to kick things of, the inital approach could be to read the yarn lock-file and generate SystemJS config.

**Comment by alexisvincent** [comment]
Yeah, agreed. However I'm unsure of how to construct a dependency tree from the lock file. I need to work out how yarn handles dependency clashes. As in who wins (gets put in top level). I have a feeling we could leverage yarn internals to get a tree.

**Comment by jonaskello** [comment]
[This issue](https://github.com/yarnpkg/yarn/issues/738) and [this issue](https://github.com/yarnpkg/yarn/issues/1446) at the yarn repo provides some more background for this project/issue.

**Comment by alexisvincent** [comment]
Alternatively, we could simply walk node_modules and build it like that

**Comment by jonaskello** [comment]
Hmm.. Thinking about it that way, walking node_modules would make it work with npm too? Interesting that there is no existing tool that already does that :-). Or maybe there is?

As you mentioned earlier, to determine the feasibility of this approach I think one thing we need to find out is exactly what transforms jspm applies on packages as it installs them.

**Comment by alexisvincent** [comment]
@jonaskello Yeah I was wondering about this as well. I haven't come across one. Most that I have seen take the opposite approach. Try resolve a file, fail, try another etc. 

This would mean it would work for npm. But not reproducibly. Unless shrink-wrap was applied.

**Comment by alexisvincent** [comment]
Agreed, it would be a pain if we worked on this and end up recreating JSPM. @guybedford is there any reason the approach we are following here won't work, that you can see?

**Comment by jonaskello** [comment]
Generating from the lock-file would be better for reproducibility and also if we want to automate the  generation of the config, a good place would probably be to run each time the lock-file is updated. Maybe yarn provides a hook for that already or it could be added.

**Comment by alexisvincent** [comment]
@jonaskello As far as I can see, generating from lock file would be the same as generating from walking node_modules. Should give us the same result if the install was handled by yarn. Im hoping theres a way to avoid building a tree (not that it's hard), but I want to minimize duplicated work here.

**Comment by alexisvincent** [comment]
I don't have time to look at this this week, I have course work that needs to be submitted, and some missed due dates. But will be able to sit down and invest some time into this towards the end of next week hopefully. @jonaskello if you want to run with getting this started that would be amazing however!

**Comment by jonaskello** [comment]
I might try a naive implementation if I can find some time.

**Comment by jonaskello** [comment]
So, when getting started I just assumed the `yarn.lock` file was in yaml format. But at a closer look it seems it is not. Not sure what format it is. The yarn source has its own parser for it. If it is not a standard format I guess we need to use that parser.

**Comment by alexisvincent** [comment]
Oh damn. Yeah, maybe add yarn as a dep and use that. Perhaps more can be used from the yarn project then just the parser?

**Comment by alexisvincent** [comment]
@jonaskello I've started the following project https://github.com/alexisvincent/systemjs-config-builder as a more general case of this project. The approach will be to trace node_modules instead of working from the yarn lock file. So we can test things out there and when we have a stable system we can pull that in as a dependency and hack on the yarn integration here.

I've also found someone else who is interested in helping with this. He built a similar thing but closely tied the build process.

If you want I'll add you as a collaborator on the other project. Let me know if you still have time to help with this.

**Comment by alexisvincent** [comment]
I found a way to do this beautifully :D Will let you know once I've cleaned it up a bit

**Comment by jonaskello** [comment]
Interesting! :-). 

Unfortunately I do not have as much time as I wish to spend on it. OTOH I really would like to see it move forward so if you need help with something specific then ping me and I will try to contribute what I can.

**Comment by alexisvincent** [comment]
I should be ok 👍 Thanks for the interest though. Good news, given this [package.json](https://github.com/alexisvincent/systemjs-config-builder/blob/master/package.json) I can now generate this [SystemJS config](https://github.com/alexisvincent/systemjs-config-builder/blob/master/generated.config.js)

Not perfect yet. But a good start :)
